name: build-image
permissions: write-all
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest]
        go-version: [ '1.22' ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ALiYun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_TOKEN }}
      - name: Docker BuildX
        run: |
          docker buildx build \
          -t registry.cn-hangzhou.aliyuncs.com/dpanel/dpanel:doc \
          --platform linux/arm64,linux/amd64,linux/arm/v7 \
          . --push
